version: '3.8'


networks:
  app-network:
    driver: bridge



services:

  api_app:
    container_name: api_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_base:5432/sistemamedico
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

    depends_on:
      - postgres_base
    networks:
      - app-network


  postgres_base:
    image: postgres:latest
    container_name: postgres_base
    hostname: postgres_base
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistemamedico
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - postgres_base


  

  
volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:/Users/David/datamedic
